# Generated by Django 3.2.25 on 2024-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240829_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrate',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(None, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
