# Generated by Django 3.2.25 on 2024-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrate',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
